In [18]:
import numpy as np
# task 1
#1)
emptyArr = np.empty((2,2))
print(emptyArr)

[[9.39e-323 1.09e-322]
 [2.47e-322 2.87e-322]]


In [19]:
#2
allOnes = np.ones((4,2))
print(allOnes)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:

#3
fullArr = np.full((3,3),7)
print(fullArr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [21]:
#4
a = np.array([[1, 2], [3, 4]])
newArr=np.zeros_like(a)
print(newArr)

[[0 0]
 [0 0]]


In [22]:
#5
newOneArr=np.ones_like(a)
print(newOneArr)

[[1 1]
 [1 1]]


In [23]:
#6
new_list = [1,2,3,4]
listArr = np.array(new_list)
print(listArr)

[1 2 3 4]


In [24]:
#problem 2
#1
rangeArr = np.arange(10,50)
print(rangeArr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
#2
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
#3
identityMatrix = np.eye(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#4
randomArray=np.random.random(30)
meanRandom = randomArray.mean()
print(meanRandom)

0.47906116854269576


In [28]:
#5
randomTenByTen = np.random.random((10, 10))
print(randomTenByTen.min(), randomTenByTen.max())

0.011298539043520184 0.9963490286015337


In [29]:
#6
z=np.zeros(10)
z[4]=1
print(z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
#7
initArr=np.array([1,2,3,4,5,6,7])
reverseArr = initArr[::1]
print(reverseArr)

[1 2 3 4 5 6 7]


In [31]:
#8
print("here")
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print(border)

here
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
#9
checker = np.zeros((8, 8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [33]:
#problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#1
print("sum of two array is:\n", x+y)
#2
print("diff of two array is:\n", x-y)
#3
print("product of an array and a scaler is:\n", 3*x)
#4
print("sq of  array is:\n", x**2)
#5
print("dot product of v & w array is:\n",np.dot(v, w))
print("dot product of x & v array is:\n",np.dot(x, v))
print("dot product of x & y array is:\n",np.dot(x, y))
#6
print("Row-wise concat of x & y array is:\n", np.concatenate((x, y), axis=0))
print("Column-wise concat of x & y array is:\n", np.column_stack((x, y)))
#7
# print("Row-wise concat of x & v array is:\n", np.concatenate((x, v), axis=0))
# gives error because the dimension are not same

sum of two array is:
 [[ 6  8]
 [10 13]]
diff of two array is:
 [[-4 -4]
 [-4 -3]]
product of an array and a scaler is:
 [[ 3  6]
 [ 9 15]]
sq of  array is:
 [[ 1  4]
 [ 9 25]]
dot product of v & w array is:
 219
dot product of x & v array is:
 [29 77]
dot product of x & y array is:
 [[19 22]
 [50 58]]
Row-wise concat of x & y array is:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column-wise concat of x & y array is:
 [[1 2 5 6]
 [3 5 7 8]]


In [34]:
#problem4
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#1
inverseA = np.linalg.inv(A)
print(A.dot(inverseA))



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [35]:
#2
AB =A.dot(B)
BA= B.dot(A)
if( np.array_equal(AB,BA) ):
    print("AB = BA")
else:
    print("AB ≠ BA")



AB ≠ BA


In [36]:
#3
LHS = (A.dot(B)).T
RHS = B.T.dot(A.T)
if( np.array_equal(LHS, RHS) ):
    print("(AB)ᵀ = Bᵀ Aᵀ")
else:
    print("(AB)ᵀ ≠ Bᵀ Aᵀ")

(AB)ᵀ = Bᵀ Aᵀ


In [ ]:
#problem 4)2
# 2x – 3y + z = -1
# x – y + 2z = -3
# 3x + y – z = 9

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print("x,y,z = ",X)

In [37]:
import time

In [42]:
#experiment
#1
# Python lists
list1 = list(range(1000000))
list2 = list(range(1000000))
pyStart = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
pyEnd = time.time()
print("Python List Addition Time:", pyEnd - pyStart, "seconds")

# NumPy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
npStart = time.time()
np_add = arr1 + arr2
npEnd = time.time()
print("NumPy Addition Time:", npEnd - npStart, "seconds")


Python List Addition Time: 0.19266843795776367 seconds
NumPy Addition Time: 0.002150297164916992 seconds


In [44]:
#2

#python list
pyTwoStart = time.time()
list_mul = [list1[i]*list2[i] for i in range(1000000)]
pyTwoEnd = time.time()
print(f"Python list multiplication time: {pyTwoEnd-pyTwoStart} seconds")

#np array
npTwoStart = time.time()
np_mul = arr1 * arr2
npTwoEnd = time.time()
print("NumPy multiplication Time:", npTwoEnd - npTwoStart, "seconds")


Python list multiplication time: 0.22205090522766113 seconds
NumPy multiplication Time: 0.004169464111328125 seconds


In [46]:
#3

#python list
pyThreeStart = time.time()
list_dotPtoduct = sum([list1[i]*list2[i] for i in range(1000000)])
pyThreeEnd = time.time()
print(f"Python list multiplication time: {pyThreeEnd-pyThreeStart} seconds")

#np array
npThreeStart = time.time()
np_dotProduct = np.dot(arr1,arr2)
npThreeEnd = time.time()
print("NumPy multiplication Time:", npThreeEnd - npThreeStart, "seconds")


Python list multiplication time: 0.16133427619934082 seconds
NumPy multiplication Time: 0.0029850006103515625 seconds


In [47]:
#4

#python list
matrix1 = [[1]*1000 for _ in range(1000)]
matrix2 = [[1]*1000 for _ in range(1000)]
pyFourStart = time.time()
list_matrixMul = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000))
                  for j in range(1000)]
                  for i in range(1000)]
pyFourEnd = time.time()
print(f"Python list matrix multiplication time: {pyFourEnd-pyFourStart} seconds")

#np array
A = np.ones((1000, 1000))
B = np.ones((1000, 1000))

npFourStart = time.time()
np_matrixMul = np.dot(A,B)
npFourEnd = time.time()
print("NumPy matrix multiplication Time:", npFourEnd - npFourStart, "seconds")


Python list matrix multiplication time: 119.9195020198822 seconds
NumPy matrix multiplication Time: 0.06737756729125977 seconds
